# ----------------- Language Pair Setup -----------------
# this is the language we are going to learn.
target_language: 
  fullname: Finnisch
  shortname: fi
  cg_language_name: fin    # for uralicNlp

# this is the language for the explanations and translations
translated_language: 
  fullname: Deutsch
  shortname: de

# ----------------- Morphological Analysis -----------------
# we use uralicNlp for morphological analysis
analyze:
  # this is used to translate the language code to the language name from the uralicNlp library
  fin: "Finnish"
    

# ----------------- Explanation Generation -----------------    
# this is the prompt that will generate an explanation for a word
explain:
  gpt_options:
    model: gpt-4-turbo-preview
    max_parallel_calls: 5
    max_retries: 3
    timeout: 120
    schema_file_path: ankigenfin/gpt-out.schema.json  
    prompt: 
      - system: |
          Der ${target_language_fullname} Language Expert analysiert Wörter auf ${translated_language_fullname} und liefert das Ergebnis in einem spezifischen JSON-Format zurück. Als Input erhält er ein Wort ('word'), mögliche Begriffsklärungen mit Fallanalyse ('disambiguations'), Etymologie ('etymology') und ein Satz ('sentence') als Kontext. Für jedes analysierte Wort gibt er eine strukturierte JSON-Antwort zurück, die folgendes enthält:
          - 'word' (das gegebene Wort), 
          - 'lemma' (die Grundform des Wortes), 
          - 'suffixes' (eine Liste mit Tupeln aus der im Wort verwendeten Endungen sowie deren Fälle und Bedeutung), 
          - 'meaning' (die Bedeutung des Wortes auf ${translated_language_fullname}) 
          - 'explanation' (Erkläre in einem kurzen und knappen Satz das Wort im Kontext des angegeben Satzes 'sentence')
          - 'sample' (Beispielsatz mit dem analysierten Wort in ${target_language_fullname} (key target-language) und ${translated_language_fullname} (key translation). Nicht der im Kontext übermittelte Satz.)

          Dieses Format sorgt für eine klare und systematische Darstellung der linguistischen Analyse. Der Expert bleibt sachlich und direkt, mit einem neutralen Ton.

          Beispiel:

          {
            "word": "elokuvassaan",
            "lemma": "elokuva",
            "suffixes": [
              {"-ssa": "inessiv; innerhalb von, in etwas drin"},
              {"-an": "3. Person Singular possessivsuffix; sein/ihr"}
            ],
            "meaning": "in seinem/ihrem Film",
            "explanation": "Das finnische Wort 'elokuva' bedeutet 'Film' oder 'Kino' auf Deutsch. Es setzt sich aus zwei Teilen zusammen: „elo“ und „kuva“.\n'Elo': Dieser Teil des Wortes stammt von „elämä“, was „Leben“ bedeutet. Es bezieht sich auf etwas Lebendiges oder Dynamisches.\n'Kuva': Dieser Teil bedeutet 'Bild' oder 'Abbildung'.", 
            "sample": {
              "target-language": "Ohjaaja esitteli uusia teemoja elokuvassaan.",
              "translation": "Der Regisseur stellte neue Themen in seinem Film vor."
            }
          }
      - user: "${word_data_with_context_str}"


# ----------------- Audio Generation -----------------
# we use elevenlabs for audio generation
audio_generation:
  model: eleven_multilingual_v2
  max_parallel_calls: 3
  max_retries: 3
  timeout: 120
  output_folder: media
  voices:
    # we select a random voice for each audio generation
    - name: Matilda
      id: "XrExE9yKIg1WjnnlVkGX"
      use_speaker_boost: true
      style: 0
      stability: 0.5
      similarity_boost: 1.0
    - name: Charlotte
      id: "XB0fDUnXU5powFXDhCwa"
      use_speaker_boost: true
      style: 0
      stability: 0.5
      similarity_boost: 1.0
    - name: Domi
      id: "AZnzlk1XvdvUeBnXmlld"
      use_speaker_boost: true
      style: 0
      stability: 0.5
      similarity_boost: 1.0
    - name: Sarah
      id: "EXAVITQu4vr4xnSDxMaL"
      use_speaker_boost: true
      style: 0
      stability: 0.5
      similarity_boost: 1.0
    - name: Lily
      id: "pFZP5JQG7iQjIQuC4Bku"
      use_speaker_boost: true
      style: 0
      stability: 0.5
      similarity_boost: 1.0



# ----------------- Machine Translation -----------------
# you can use deepl or gpt for machine translation
# deepl is cheaper and faster, but gpt is more accurate
# if you use gpt, you can choose the model, and adjust the prompt if nessesary
machine_translation:
  use_deepl: false
  use_gpt: true
  gpt_options:
    model: gpt-4-turbo-preview
    max_parallel_calls: 5
    max_retries: 3
    timeout: 120
    prompt: 
      - system: "Bitte übersetze das json im Kontext von ${source_language_fullname} nach ${target_language_fullname}"
      - assistant: "Wie lautet der Kontext?"
      - user: "${context}"
      - assistant: "Wie lautet das Json, welches übersetzt werden soll?"
      - user: "${json_string}"

# ----------------- Anki -----------------
# we create anki cards with explanations and media
anki_card:
  id: 1865967360 # 
  name: Card with Explanation & Media
  fields: 
    - Finnish
    - English
    - Explanation
    - HasReverse
    - Media
  templates:
    - name: Card Finnish => English
      qfmt: '<div class="front"><span>{{Finnish}}</span><span style="float: right;">{{Media}}</span></div>'
      afmt: '{{FrontSide}}<div class="back">{{English}}</div>{{Explanation}}'
    - name: Card English => Finnish
      qfmt: '{{#HasReverse}}{{English}}{{/HasReverse}}'
      afmt: '{{FrontSide}}<div class="back"><span>{{Finnish}}</span><span style="float: right;">{{Media}}</span></div>{{Explanation}}'
  css_path: anki-card-template/style.css
  explanation_template: anki-card-template/explanation.html
